### ISSUE TITLE
Remarks on Go's plugin system

### ISSUE THREAD

**Issue by gunnihinn** [awesome-flow/flow#3]
This isn't really an issue, just some stuff I've seen while looking into Go's plugin system.

I've found some hints in the Go mailing lists that back up what's claimed in [this Reddit comment](https://www.reddit.com/r/golang/comments/5zaojs/a_practical_example_of_using_gos_18_plugin_system/dexa3yb). It claims that the plugin system has the following limitations:

1. A plugin must be compiled with the same Go toolchain as the code it will be used in.
2. Any common dependencies between the plugin and the code must be the same.

[This discussion](https://groups.google.com/forum/#!searchin/golang-nuts/plugin|sort:date/golang-nuts/4q3KwJoCNdE/yRDn1-BkAwAJ) on Go-nuts and [this issue](https://github.com/golang/go/issues/21373) seem to confirm (1).

I guess both (1) and (2) follow from how the plugin system is supposed to work. It just makes plugin symbols available to outside programs, and if those symbols point to other symbols (that is, standard library dependencies or 3rd party dependencies) you get problems (1) and (2), respectively, if you want to be sure that the plugin behaves correctly.

It's probably easier to deal with (1) in an open source project, as plugin users have the sources for everything they want at compile time. (2) might be trickier, as a plugin and the core might both depend on different, incompatible versions of the same 3rd package. No amount of vendor or modules can deal with that. (This is a problem as well with (1), but we can probably count on the standard library being backwards API compatible.)

If this is more or less correct, then a core system that wants to go all-in on plugins should use as few third-party dependencies as possible, and of the ones it uses, carefully choose ones whose maintainers have proven to care deeply about backwards API compatibility. (Or defer all of its third-party dependencies to plugins itself? Want logging? Provide a plugin that implements an interface. Seems hairy.)

**Comment by icanhazbroccoli** [comment]
Hey @gunnihinn, well, you are absolutely right. The plugin system is super immature yet and Flow is only about to decide how exactly this plugin ecosystem would be built and managed. What seems to be clear so far is: we need plugin support in Flow and without it the development workflow would be totally different from the planned one (developers will have to use Flow as a dependency library and build the executable binary themselves). It's not the end of the world for sure, we have to find the best way now.

I really appreciate the references you posted!

**Comment by icanhazbroccoli** [comment]
I ran a bunch of experiments with plugin compilation problems. Effectively, it boils down to the necessity of building flow plugins with the same version of Flow. It means the versions of the plugins should be aligned with the core tool. Doesn't sound like a show stopper, at least for now :-)
